title: Alexis Jeandeau
url: https://alexis.jeandeau.fr
lang: en-US
languages:
  - en
  - fr
  - ja
exclude:
  - config.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - spec
  - .rspec
  - .rubocop.yml
  - .solargraph.yml
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .bundle/
  - .github/
  - .vscode/
plugins:
  - jekyll-minifier
  - jekyll-multiple-languages-plugin
  - jekyll-seo-tag
jekyll-minifier:
  remove_intertag_spaces: true
